### ISSUE TITLE
Error to run test.py in nodemcu esp8266 board

### ISSUE THREAD

**Issue by baponkar** [micropython-Chinese-Community/mpy-lib#7]
I have insert bmp280 and test.py into esp8266 board by using ampy.after I have tried 'ampy -p /dev/ttyUSB0 -b 115200 run test.py' but it is showing :
```
Traceback (most recent call last):
  File "/usr/local/bin/ampy", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ampy/cli.py", line 337, in run
    output = board_files.run(local_file, not no_output)
  File "/usr/local/lib/python3.6/dist-packages/ampy/files.py", line 303, in run
    out = self._pyboard.execfile(filename)
  File "/usr/local/lib/python3.6/dist-packages/ampy/pyboard.py", line 273, in execfile
    return self.exec_(pyfile)
  File "/usr/local/lib/python3.6/dist-packages/ampy/pyboard.py", line 267, in exec_
    raise PyboardError('exception', ret, ret_err)
ampy.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 15, in <module>\r\n  File "bmp280.py", line 20, in __init__\r\n  File "bmp280.py", line 60, in get2Reg\r\n  File "bmp280.py", line 55, in getReg\r\nOSError: [Errno 110] ETIMEDOUT\r\n')

```
I am using Ubuntu 18.04 terminal to upload the code.How can I resolve this issue?

**Comment by shaoziyang** [comment]
please try to upload file again, or use upyloader to upload files.

**Comment by baponkar** [comment]
Thankyou
